config/routes.rb
Vertatweet2::Application.routes.draw do
  root to: "application#index"
  resources :maps, only: %i{ create } do
    get "show_one", on: :collection
  end
  resources :keywords, only: %i{ create } do
    post "scan", on: :collection
  end

  

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :map
end

app/models/map.rb
class Map < ActiveRecord::Base
  has_many :points

  before_validation do |record|
    record.country = record.name
  end
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :map
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/keywords_controller.rb
class KeywordsController < ActionController::Base
  def create
    keyword = Keyword.create(keyword_params)
    respond_to do |f|
      f.json do
        render json: keyword.to_json
      end
    end
  end

  def scan
    Keyword.find(params[:id])
    Scanner.scan(Keyword.name, Keyword.map.points.to_a)
  end

  private
    def keyword_params
      params.
        require(:keyword).
        permit(:name, :map_id)
    end
end

app/controllers/maps_controller.rb
class MapsController < ActionController::Base
  def show_one
    map = Map.find(params[:id])
    respond_to do |f|
      f.json do
        render json: map.points.to_a.to_json
      end
    end
  end

  def create
    map = Map.create(map_params)
    griddable = Geocoder::Griddable.new(geocoder_params)
    grid = griddable.to_grid(radius_params)
    grid.lines.each do |line|
      line.each do |point|
        Point.create(map: map,
                     lat: point.lat,
                     lng: point.lng,
                     radius: point.km_radius)
      end
    end
    respond_to do |f|
      f.json do
        render json: grid.lines
      end
    end
  end

  private
    def geocoder_params
      params.
        require(:griddable).
        permit(%i{ top_left bottom_right name }).
        merge(rule: "country")
    end

    def radius_params
      params.
        require(:griddable).
        permit(:radius)["radius"].to_i
    end

    def map_params
      params.
        require(:griddable).
        permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Title
    = stylesheet_link_tag "application", :media => "all"
  %body
    .container
      .row
        .span7
          = render partial: "maps/map"
        .span5
          %ul.nav.nav-tabs#tabs
            %li
              %a{href: "#create-map", "data-toggle" => "tab"} Create
            %li
              %a{href: "#_show-map", "data-toggle" => "tab"} Show
            %li
              %a{href: "#keyword", "data-toggle" => "tab"} Keyword
            %li
              %a{href: "#_scan-keyword", "data-toggle" => "tab"} Scan Keyword
          #tabs-content
            #create-map.active
              = form_for :griddable, url: maps_path, remote: true, html: {id: "griddable-form"} do |f|
                %b Radius <br/>
                = f.text_field :radius
                %br/

                %b Country Name <br/>
                = f.text_field :name, class: "country-name"
                %br/

                %b Top Left <br/>
                = f.text_field :top_left, class: "top-left"
                %br/

                %b Bottom Right <br/>
                = f.text_field :bottom_right, class: "bottom-right"
                %br/

                = f.submit "Create Map"
            #_show-map
              = form_tag show_one_maps_path("lol" => Time.now.to_i.to_s), remote: true, id: "show-map", method: :get do
                = select_tag "id", options_for_select(Map.all.map {|m| ["#{m.name}-#{m.id}", m.id]})
                = submit_tag "Show"
            #keyword
              = form_for Keyword.new, remote: true, id: "create-keyword", method: :post do |f|
                %b Name <br/>
                = f.text_field :name
                %br/
                %b Country <br/>
                = f.select :map_id, Map.all.map{|m|[%Q{#{m.name}-#{m.id}},m.id]}
                = f.submit "Create"
            #_scan-keyword
              = form_tag scan_keywords_path, id: "scan-keyword", method: :post, remote: true do
                = select_tag "id", options_for_select(Keyword.includes(:map).all.map{|k|[%Q{#{k.name}-#{k.map.try(:name)}-#{k.map.try(:id)}},k.id]})
      .row
        -# = yield

    %script{type: "text/javascript", src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyBfCvgH3uq19q9kywAa2Xj3vHR3GuT9R64&sensor=false"}
    = javascript_include_tag "application"

app/views/maps/_map.html.haml
#map-canvas